# Docker Swarm stack that runs the cleanup script on every node
services:
  swarm_cleanup:
    image: alpine:3.19
    environment:
      REPO_URL: "${REPO_URL:-https://github.com/tanngoc93/swarm-stackhouse.git}"
      REPO_DIR: "${REPO_DIR:-/tmp/swarm-stackhouse}"
      SCRIPT: "${SCRIPT:-scripts/cleanup_docker_images.sh}"
      IMAGE_REPO: "${IMAGE_REPO}"
      DRY_RUN: "${DRY_RUN:-0}"
      RM_TIMEOUT: "${RM_TIMEOUT:-20s}"
      RUN_TIMESTAMP: "${RUN_TIMESTAMP}"
    command: >
      sh -c "
        set -e;
        echo '--- [Swarm Cleanup] running on node: '$$(hostname);
        apk add --no-cache git bash docker-cli >/dev/null;
        rm -rf $$REPO_DIR &&
        git clone --depth=1 $$REPO_URL $$REPO_DIR;
        chmod +x $$REPO_DIR/$$SCRIPT;
        DRY_RUN=$$DRY_RUN RM_TIMEOUT=$$RM_TIMEOUT IMAGE_REPO=$$IMAGE_REPO bash $$REPO_DIR/$$SCRIPT;
        echo '--- Done on node: '$$(hostname);
        exit 0
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: none
